- id: user
  label: User ID.
  description: Anonymous identification for your session.
  input: input

- id: app.hardwareAcceleration
  label: Hardware acceleration.
  description: Can improve performance on some devices.<br>* Requires restart to take effect.
  tooltip: Use your GPU to increase application performance. (This does **not** include the nudification algorithm)
  input: checkbox

- id: app.uploadMode
  label: Open mode.
  description: How open files will behave.
  tooltip: |-
    - **Pending:** Stay on the current page and wait to start the nudification manually.
    - **Preferences:** Move to photo preferences automatically. In case of uploading multiple files, it will move to the preferences of the last photo.
    - **Queue:** Begin nudification as soon as the file is opened. (The default preferences are used which may return poor quality results.)
  input: select
  options:
    - label: Pending
      value: none
    - label: Preferences
      value: go-preferences
    - label: Queue
      value: add-queue

- id: app.duplicates
  label: Allow duplicates.
  description: Allow the upload of the same photo multiple times.
  tooltip: |-
    With this you can upload a photo multiple times and set different preferences or crop areas without having to wait, this will also make the photos show a unique identification to be able to differentiate.
  input: checkbox

- id: app.legacyUploader
  label: Legacy Uploader.
  description: Use the old uploader instead of Uppy.
  tooltip: |-
    The new uploader (Uppy) allows you to upload photos from your Dropbox and Google Drive, as well as view, delete and edit the photos before uploading them. The downside is that it requires an internet connection.
  input: checkbox

- id: app.showStats
  label: Show system stats.
  description: Show system usage statistics.
  tooltip: |-
    Allows you to check `RAM Usage` or `VRAM Usage`. Problems with the algorithm usually occur when one of these is too high.

    > Enabling this option can consume more system resources, especially in Windows.
  input: checkbox

- id: app.trypophobiaMode
  label: Trypophobia mode.
  description: Removes images that can trigger trypophobia.
  input: checkbox

- id: app.resultsColumns
  label: Results columns.
  description: How many columns display on the results page.
  input: select
  options:
    - label: Automatic
      value: auto
    - label: 1
      value: 1
    - label: 2
      value: 2
    - label: 3
      value: 3
    - label: 4
      value: 4
    - label: 5
      value: 5
    - label: 6
      value: 6

- id: app.queuePosition
  label: Queue position.
  description: Change the position of the queue bar.
  input: select
  options:
    - label: Right
      value: right
    - label: Left
      value: left

- id: app.showAds
  label: Show ads.
  description: Support development and show ads at the bottom of the menu.
  tooltip: The displayed advertisements are selected by DreamNet and allow to support the DreamTime development.
  input: checkbox

- id: app.showTips
  label: Show tips.
  description: Show help tips at the bottom of the menu.
  input: checkbox

- id: preferences.advanced.device
  label: Device.
  description: GPU is faster but depends on the device VRAM.<br>CPU is slower but uses system RAM.
  tooltip: |-
    Nudification times:
    ---

    - **NVIDIA GPU:** Between 5 and 60 seconds.
    - **CPU:** Between 1 and 15 minutes.
  input: select
  options:
    - label: CPU
      value: CPU
    - label: NVIDIA GPU
      value: GPU

- id: processing.gpus
  label: GPU Slot.
  description: Graphics card to use.

- id: processing.cores
  label: Video workers.
  description: "More workers increases the nudification speed for <b>Videos and GIFs</b> but can decrease system stability.<br>Recommended: 1"
  input: input

- id: preferences.mode
  label: Preferences Mode.
  description: Complexity of options.
  tooltip: |-
    - **Minimal**: Only the body preferences are shown, all other options will be set to make the process as automatic as possible.
    - **Simple**: Same as `Minimal` but you can change the `Scale method`.
    - **Normal**: All options available, this is the original DreamTime experience.
    - **Custom masks**: Advanced mode that requires experience and time. In this mode you will work with the masks generated by the algorithm making manual modifications to each one of them, this allows to drastically improve the quality of the fake nude if it is done correctly.
      - The `Nudify` or `Start` buttons are disabled for the photo since the masks must be generated one by one.
      - The `Per run` preferences are disabled.
  input: select
  options:
    - label: Minimal
      value: 0
    - label: Simple
      value: 1
    - label: Normal
      value: 2
    - label: Custom masks
      value: 3
  animated-options:
    - label: Minimal
      value: 0
    - label: Simple
      value: 1
    - label: Normal
      value: 2

- id: preferences.advanced.scaleMode
  label: Scale method.
  description: Indicates how the photo will be scaled to a size compatible with the algorithm.
  tooltip: |-
    - **None:** The algorithm will be forced to process the photo using an approximation of its original size. This option can considerably increase memory consumption and return worse results.
    - **Automatic Resize:** Automatic resize **without** maintaining the aspect ratio.
    - **Automatic Padding:** Automatic resize maintaining the aspect ratio.
    - **Automatic Crop:** Automatic crop maintaining the aspect ratio.
    - **Overlay:** Allows you to select the area of the photo you want to nudify keeping the original size of the photo.
    - **Crop:** Allows you to crop the area of the photo you want to nudify. (Like in DeepNude)
    - **Color padding:**  Add a black and white padding that avoids color change and can return much better fake nude in some photos.
  input: select
  options:
    - label: None
      value: none
    - label: "Automatic Resize"
      value: auto-rescale
    - label: "Automatic Padding"
      value: auto-resize
    - label: "Automatic Crop"
      value: auto-resize-crop
    - label: Overlay
      value: overlay
    - label: Crop
      value: cropjs
    - label: Color Padding
      value: padding
  animated-options:
    - label: None
      value: none
    - label: "Automatic Resize"
      value: auto-rescale
    - label: "Automatic Padding"
      value: auto-resize
    - label: "Automatic Crop"
      value: auto-resize-crop

- id: preferences.body.runs.mode
  label: Mode.
  description: How the body preferences will be changed in each run.
  tooltip: |-
    - **Randomize:** Each run will have random body preferences.
    - **Increase by Step:** Each run will increase the body preferences by the specified step.
  input: select
  options:
    - label: Disabled
      value: false
    - label: Randomize
      value: randomize
    - label: Increase by Step
      value: increase

- id: preferences.body.runs.count
  label: Count.
  description: Number of times the photo will be nudified.
  input: input
  attrs:
    type: number
    min: 2

- id: preferences.body.runs.rate
  label: Step.
  input: input
  attrs:
    type: number
    min: 0.02
    step: 0.02
    max: 2

- id: preferences.advanced.useColorPaddingStrip
  label: Color Padding Removal.
  description: Automatically remove the color padding mask.
  input: checkbox

- id: preferences.advanced.useColorTransfer
  label: Color Transfer.
  description: Try to recover the original colors of the photo.
  input: checkbox

- id: preferences.advanced.useArtifactsInpaint
  label: Visual Artifacts Inpaint.
  description: Try to remove the visual artifacts that appears in the vagina.
  input: checkbox

- id: preferences.advanced.useClothTransparencyEffect
  label: X-Ray Tool.
  description: Create an X-Ray effect with the fake nude.
  tooltip: |
    Enable the `X-Ray Tool` allowing you to add the photo with clothes on top of the fake nude and modify the transparency to achieve the effect.

    - The photo exported from this tool may have lower quality than the fake nude.
    - The photo will be exported in the size indicated by the `Image size` option. (Increased size by Waifu2X are ignored.)
  input: checkbox

- id: preferences.advanced.imageSize
  label: Image size.
  description: Sets the internal size of the photo that the algorithm will accept. Sizes other than 512x512 can consume more memory and give worse results.
  input: select
  options:
    - label: 256x256
      value: 256
    - label: 512x512
      value: 512
    - label: 768x768
      value: 768
    - label: 1024x1024
      value: 1024
    - label: 1280x1280
      value: 1280

- id: preferences.advanced.compress
  label: Compression level.
  description: High level of compression sacrifices quality for less memory consumption.
  input: select
  options:
    - label: Disabled
      value: 0
    - label: Low
      value: 25
    - label: Medium
      value: 50
    - label: High
      value: 75

- id: preferences.advanced.waifu.enabled
  label: Waifu2X.
  description: Use the algorithm to upscale & denoise the fake nude.
  input: checkbox

- id: preferences.advanced.waifu.scale
  label: Upscale ratio.
  description:
  input: select
  options:
    - label: Disabled
      value: 1
    - label: 2x
      value: 2
    - label: 3x
      value: 3
    - label: 4x
      value: 4

- id: preferences.advanced.waifu.denoise
  label: Denoise level.
  description:
  input: select
  options:
    - label: Disabled
      value: 0
    - label: Low
      value: 1
    - label: Medium
      value: 2
    - label: High
      value: 3

- id: preferences.advanced.waifu.tta
  label: TTA level.
  description: Can increase the quality of the upscale but it will take more time.
  input: select
  options:
    - label: Disabled
      value: 0
    - label: Low
      value: 2
    - label: Medium
      value: 4
    - label: High
      value: 8

- id: preferences.advanced.waifu.arch
  label: Model.
  description: Each model can give different results in each photo.
  input: select
  options:
    - label: VGG7
      value: 0
    - label: UpConv7
      value: 1
    - label: ResNet10
      value: 2
    - label: UpResNet10
      value: 3

- id: notifications.run
  label: Every run.
  description: Notify when the program is not in the foreground and a single run have finished.
  input: checkbox

- id: notifications.allRuns
  label: Every dream.
  description: Notify when the program is not in the foreground and all the runs have finished.
  input: checkbox

- id: notifications.update
  label: Update available.
  description: Notify when there is a new version of DreamTime, DreamPower or the checkpoints.
  input: checkbox

- id: folders.cli
  label: DreamPower.
  description: Nudification algorithm.

- id: folders.waifu
  label: Waifu2X.
  description: Upscale and denoise algorithm.

- id: folders.models
  label: Models.
  description: Final nudes.

- id: folders.cropped
  label: Temporal.
  description: Temporary files for processing.

- id: telemetry.bugs
  label: Error report.
  description: Allow to report errors automatically.
  tooltip: |-
    - Operating system.
    - CPU, RAM and GPU.
    - User settings.
    - Console log.
  input: checkbox

- id: telemetry.dom
  label: Session tracking.
  description: Allow to send detailed information on how you use the application.
  tooltip: |-
    - Operating system.
    - CPU, RAM and GPU.
    - User settings.
    - Console log.
    - Actions inside the application. (Photos and sensitive information are censored.)
  input: checkbox
