name: Build

on:
  push:
    branches:
      - canary

jobs:
  build:
    name: ${{ matrix.platform }} (${{ matrix.type }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - windows-latest
        type:
          - installer

    steps:
      - name: Check
        uses: actions/checkout@v2

      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Dependencies
        working-directory: src/
        run: yarn install

      - name: Installer
        working-directory: src/
        run: yarn run build

      - name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dreamtime-${{ matrix.platform }}-${{ matrix.type }}
          path: |
            dist/*.7z
            dist/*.exe