name: Build

on:
  push:
    branches:
      - canary

jobs:
  setup:
    name: Setup
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Install Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        env:
          cache-name: setup-modules
        with:
          path: src/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('src/yarn.lock') }}

      - name: Install Dependencies
        working-directory: src
        run: yarn install

  build-electron:
    name: "Electron: ${{ matrix.type }} - ${{ matrix.target }} (${{ matrix.os }})"
    needs: setup
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        type: [installer]

    steps:
      - name: Install Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        env:
          cache-name: setup-modules
        with:
          path: src/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('src/yarn.lock') }}

      - name: Build - Electron entry
        working-directory: src
        run: yarn run build:babel

      - name: Build - NuxtJS
        working-directory: src
        run: yarn run build:nuxt

      - name: Build ENV
        working-directory: src
        env:
          GITHUB_SHA: ${{ github.sha }}
          BUILD_PORTABLE: ${{ matrix.type == 'portable' }}
          BUILD_TARGET: ${{ matrix.target }}
        run: yarn run build:env

      - name: Build Electron
        working-directory: src
        run: yarn build:electron

      - uses: actions/upload-artifact@v2
        with:
          name: dreamtime-${{ matrix.os }}-${{ matrix.type }}-${{ matrix.target }}
          path: |
            dist/*.7z
            dist/*.exe